### ISSUE TITLE
Different data type in case statement

### ISSUE THREAD

**Issue by broncha** [mWater/mwater-expressions#40]
When cases in expressions are of different data type, currently we are only looking at the first one. This causes issues when we have different types.
eg. text type in case 0 and enumset in case 1.

If the second condition is met, the enum values are not transformed

**Comment by grassick** [comment]
I can't imagine why a case would want to return two different datatypes. The expressions system doesn't support variable type expressions and I think the first case should define the type for the subsequent ones. I believe that's how getExprType figures out the type of case expressions.

**Comment by broncha** [comment]
here is the case that brought this up. The if statement is a text type and else is enumset
Works as expected when the cases are reversed. That's the solution I replied to him.

![screen shot 2017-12-27 at 12 06 15 pm](https://user-images.githubusercontent.com/46905/34386111-34ccdf96-eb4f-11e7-9c40-d0062e5368cf.png)

**Comment by grassick** [comment]
Baye defon is an enum set? Definitely shouldn't be a return type along with
Ho General

**Comment by broncha** [comment]
Yes "Baye defon" is an enum set. But since the first case is a text type. Its treated as text, and the ids of the enum values from "Baye defon" are shown.

**Comment by grassick** [comment]
Ya, definitely shouldn't be allowed. All later "thens" should be forced to be same type as first.

There is a "Convert to text" function for cases like this where an enum needs to become a plain text string.

**Comment by broncha** [comment]
closed with the updates here https://github.com/mWater/mwater-expressions/pull/63
