### ISSUE TITLE
Expression "Number of values in" does not account for null responses

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-expressions#42]
When adding a "Number of values in" filter for a multichoice question with a less than operator does not count entirely blank responses.

[https://portal.mwater.co/#/dashboards/80a95dcf7b264c3b9d59ef51872ee8dd](https://portal.mwater.co/#/dashboards/80a95dcf7b264c3b9d59ef51872ee8dd)

**Comment by grassick** [comment]
length operator now returns 0 for null. In next release!
