### ISSUE TITLE
Allow Date and Datetime comparisons

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-expressions#50]
When a user wants to see a date between two dates and one is a date data type and the other datetime, we should allow this to work. In these instances can we convert the datetime to a date, or else use the midnight time or similar?

**Comment by grassick** [comment]
We could truncate the datetime to a GMT date. That would make it clearer that the comparison really can't be done properly. Or, we assume midnight GMT. 

Either could work. I'd vote for midnight GMT, personally.

**Comment by Autio** [comment]
I'm fine with midnight GMT.
